blockFields:
- id: ProductList
  type: Pointer
  name:
    en-US: Product list
    sv-SE: Produktlista
  settings:
    multiCulture: false
    administration:
      columns: false
      filter: false
      readonly: false
    storefront:
      visible: true
      searchable: false
  option:
    entityType: ProductsProductList
    multiSelect: false
