websiteTemplates:
- blockContainers:
  - id: Main
    name:
      sv-SE: 
      en-US: 
    childBlocks:
      combination: IncludeSelected
      selections:
      - id: Banner
  settings:
    indexThePage: true
  type: Page
  fieldGroups:
  - id: Settings
    name:
      en-US: Settings
      sv-SE: Inställningar
    fields:
    - id: _name
    - id: _url
    - id: ProductList
    administration:
      collapsed: false
    storefront:
      visible: false
  id: ProductList
  name:
    en-US: Product list
    sv-SE: Produktlista
